In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## senteces

sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]


In [3]:
##Define the vocabulary size
voc_size=10000

In [4]:
##One hot Represetatiton
one_hot_repr= [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3994, 3100, 7484, 9159],
 [3994, 3100, 7484, 8123],
 [3994, 6334, 7484, 8139],
 [4920, 7557, 6757, 8913, 9164],
 [4920, 7557, 6757, 8913, 6729],
 [8909, 3994, 2053, 7484, 4861],
 [4160, 8173, 5675, 8913]]

In [5]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
##precisamos de ter as frases todas do mesmo tamanho
sent_length=8

embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3994 3100 7484 9159]
 [   0    0    0    0 3994 3100 7484 8123]
 [   0    0    0    0 3994 6334 7484 8139]
 [   0    0    0 4920 7557 6757 8913 9164]
 [   0    0    0 4920 7557 6757 8913 6729]
 [   0    0    0 8909 3994 2053 7484 4861]
 [   0    0    0    0 4160 8173 5675 8913]]


In [8]:
##feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Frejsen Wise\SimpleRNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step


array([[[-0.01800786, -0.01941001,  0.03429761, -0.04964197,
         -0.04590461, -0.01804166,  0.01320844, -0.0422015 ,
         -0.02553461,  0.02149227],
        [-0.01800786, -0.01941001,  0.03429761, -0.04964197,
         -0.04590461, -0.01804166,  0.01320844, -0.0422015 ,
         -0.02553461,  0.02149227],
        [-0.01800786, -0.01941001,  0.03429761, -0.04964197,
         -0.04590461, -0.01804166,  0.01320844, -0.0422015 ,
         -0.02553461,  0.02149227],
        [-0.01800786, -0.01941001,  0.03429761, -0.04964197,
         -0.04590461, -0.01804166,  0.01320844, -0.0422015 ,
         -0.02553461,  0.02149227],
        [ 0.01823745,  0.01051525,  0.04873915, -0.03986465,
         -0.0319054 , -0.04465898,  0.01976652, -0.03364066,
          0.02518597, -0.03139613],
        [-0.04828103, -0.03128166, -0.04075737, -0.03744144,
          0.01556024,  0.04942843, -0.00598101, -0.00318711,
          0.01541397, -0.00111957],
        [ 0.00561098,  0.03057924, -0.01882019, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 3994, 3100, 7484, 9159])